### ISSUE TITLE
Mise en place des packs de produits

### ISSUE THREAD

**Issue by fredkim-dev** [fredkim-dev/nobless-shop#1]
Permet l’ajout au panier de plusieurs produits en une fois

Voir [ce bundle](https://packagist.org/packages/sylius/product-bundle)

**Comment by fredkim-dev** [comment]
Hello,

Si tu peux commencer par ce dev, ce serait top :)

**Comment by j0r1s** [comment]
Hello @fredkim-dev, bonne nouvelle ! Je me suis renseigné sur slack au sujet du [plugin](https://github.com/BitBagCommerce/SyliusProductBundlePlugin) : 
![image](https://user-images.githubusercontent.com/35805130/78568425-65c74200-7822-11ea-87a6-ba5d4a2d4d7f.png)

Visiblement on pourrait l'utiliser. je mets ca en place demain si c'est bon pour toi.

**Comment by fredkim-dev** [comment]
Ok !
Cool, bon bah finalement, ce sera plutôt rentable juste pour une installation de plugin 😂 

Est-ce que si ça rentre dans les 2 jours prévus, il te serait possible de créer une fonction qui permettrait de remonter une collection de bundles composés des 4 derniers + 6 bundles aléatoires ?
Si ça ne rentre pas, ce n'est pas grave, je m'en occuperai ^^

Merci !
