### ISSUE TITLE
Développement du programme de fidélité

### ISSUE THREAD

**Issue by fredkim-dev** [fredkim-dev/nobless-shop#2]
En tant que client, vous aurez la possibilité de cumuler des euros à chaque euro dépensé.
La cagnotte sera ensuite utilisable dès la deuxième commande.
Règle : 10€ dépensés = 1€ cumulé

Dans la page panier, le client aura la possibilité de choisir le montant de sa cagnotte à soustraire au montant de la commande.
Cela s’applique au montant TTC de la commande sans les frais de port.

Il faudrait peut-être envisager d'afficher le montant de cette cagnotte dans l'admin au niveau du client sans possibilité de le changer

**Comment by fredkim-dev** [comment]
Hello @j0r1s 
Des petites précisions sur ce système de cagnotte :
- La somme payée est la somme sur laquelle il faut se baser pour faire le cumul de la cagnotte, on arrondit à l'entier inférieur
- La cagnotte est à soustraire au sous-total (les frais de port ne sont pas impactés)
- Le client doit pouvoir voir sa cagnotte dans son dashboard

N'hésite pas si tu as des questions

**Comment by fredkim-dev** [comment]
La branche dev est à jour, tu peux partir de celle-là pour faire ta branche de feature :)

**Comment by j0r1s** [comment]
En admin il faut créer la stratégie, ça se passe dans le sous-menu "Marketing" : 
![image](https://user-images.githubusercontent.com/35805130/106386130-d2c04f80-63d3-11eb-9866-395c07ffc997.png)

Ici on configure la réduction appliquée (dans le screenshot, 10% du montant de la commande sera attribué en points). 

Et les règles pour lesquels les points bonus doivent être attribués, j'ai créé un service `NoRuleChecker` qui retourne `true` afin que les points bonus soit appliqués à chaque commande.
Il existait dans le plugin un autre `Checker` qui permet de choisir les taxonomies des produits sur lesquels les bonus points doivent être attribués.

J'ai aussi rajouté un admin basique qui liste les enregistrements de la table bonus points : 
![image](https://user-images.githubusercontent.com/35805130/106386787-f638c980-63d6-11eb-8216-5f9c354bdfa9.png)

On pourra peut être améliorer cet affichage mais la colonne `isUsed` indique si les points bonus ont été "gagnés" ou "utilisés" dans cette commande.

Pour le front j'ai repris ton JS et adapté pour l'input des points bonus : 
(Si pas de point bonus disponible pour le customer alors rien ne s'affiche)

![image](https://user-images.githubusercontent.com/35805130/106386079-8c6af080-63d3-11eb-9b3b-268f55b71380.png)

Je gère les retours d'erreur de la même façon : 
![image](https://user-images.githubusercontent.com/35805130/106386091-a1e01a80-63d3-11eb-9e26-a695f92be0fc.png)

N'hésite pas si tu as des retours / questions !
